name: Java CI with Gradle and Docker Build/Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

  docker-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    # Login to Docker registry
    - name: Login to JFrog Artifactory Docker Registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login rkss.jfrog.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Build Docker image
    - name: Build Docker image
      run: docker build -t rkss.jfrog.io/build-and-push-docker-local/rkimage:latest .

    # Push Docker image to registry
    - name: Push Docker image
      run: docker push rkss.jfrog.io/build-and-push-docker-local/rkimage:latest
