name: UTILS.BUILD.SECRETS-SCAN

on:
  workflow_call:

jobs:

  SECRETS-SCAN:

    runs-on: ubuntu-latest

    steps:

      - name: CHECKOUT
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: INSTALL
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin v3.79.0

      - name: TRUFFLEHOG OSS
        continue-on-error: true
        run: |
          trufflehog --github-actions --only-verified --fail filesystem ./